pipeline:

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - export KUBE_NAMESPACE=$$NOTPROD_KUBE_NAMESPACE
      - export KUBE_TOKEN=$$NOTPROD_KUBE_TOKEN
      - export KUBE_SERVER=$$NOTPROD_KUBE_SERVER
      - kd -f deployment.yml
    secrets:
      - NOTPROD_KUBE_NAMESPACE
      - NOTPROD_KUBE_TOKEN
      - NOTPROD_KUBE_SERVER
    when:
      event: [push, tag, deployment]
