---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: data-transfer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: data-transfer
    spec:
      containers:
      - name: data-transfer
        image: quay.io/ukhomeofficedigital/data-transfer:v0.1.1 
        securityContext:
          runAsNonRoot: true
